# Generated by Django 3.2.14 on 2022-07-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='camera',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
